[workspace]
members = [
    "kernel",
    "userlib",
    "boot",

    "modules/gmanager",
    "modules/pci-rs",
    "modules/simple-bitmap",
    "modules/syscall-table",
    "modules/systable-macro-derive",
    "modules/plic",
    "modules/uart",


    "apps/cat",
    "apps/echo",
    "apps/dbfs",
    "apps/init",
    "apps/ls",
    "apps/mkdir",
    "apps/pwd",
    "apps/shell",
    "apps/time",
    "apps/filetest_simple",
    "apps/forktest",
    "apps/hugewrite",
    "apps/dbwrite",
    "apps/hugeread"
]


[profile.release]
#lto = "fat"
#codegen-units = 1
