[workspace]
resolver = "2"
members = [
    "kernel",
    "userlib",
    "boot",
    "modules/gmanager",
    "modules/basemachine",
    "modules/input2event",
    "apps/slint-helper",
    "apps/cat",
    "apps/sleep",
    "apps/todo",
    "apps/printdemo",
    "apps/egui",
    "apps/sysinfo",
    "apps/init",
    "apps/ls",
    "apps/mkdir",
    "apps/pwd",
    "apps/shell",
    "apps/touch",
    "apps/run_test",
    "apps/guitest",
    "apps/slint",
    "apps/socket_test",
    "apps/tests",
    "apps/memory-game",
    "apps/print",
    "apps/final_test",
]


[profile.release]
#lto = true
#codegen-units = 1
