[workspace]
resolver = "2"
members = [
    "kernel",
    "userlib",
    "boot",
    "modules/gmanager",
    "modules/pci-rs",
    "modules/syscall-table",
    "modules/systable-macro-derive",
    "modules/plic",
    "modules/syscall",
    "modules/basemachine",
    "modules/pager",
    "modules/kernel-sync",
    "modules/virtio-input-decoder",
    "modules/input2event",
    "modules/uart",
    "modules/simple-net",
    "apps/slint-helper",
    "apps/cat",
    "apps/sleep",
    "apps/todo",
    "apps/printdemo",
    "apps/egui",
    "apps/sysinfo",
    #    "apps/dbfs",
    "apps/init",
    "apps/ls",
    "apps/mkdir",
    "apps/pwd",
    "apps/shell",
    "apps/filetest_simple",
    "apps/hugewrite",
    "apps/hugeread",
    "apps/touch",
    "apps/throughput",
    "apps/randrw",
    "apps/sequencewr",
    "apps/run_test",
    "apps/guitest",
    "apps/slint",
    "apps/socket_test",
    "apps/tests",
    "apps/memory-game",
    "apps/print",
]


[profile.release]
#lto = true
#codegen-units = 1
