[workspace]
resolver = "2"
members = [
    "kernel",
    "user/userlib",
    "subsystems/gmanager",
    "user/apps/slint-helper",
    "user/apps/cat",
    "user/apps/sleep",
    "user/apps/todo",
    "user/apps/printdemo",
    "user/apps/egui",
    "user/apps/sysinfo",
    "user/apps/init",
    "user/apps/ls",
    "user/apps/mkdir",
    "user/apps/pwd",
    "user/apps/shell",
    "user/apps/touch",
    "user/apps/run_test",
    "user/apps/slint",
    "user/apps/socket_test",
    "user/apps/tests",
    "user/apps/memory-game",
    "user/apps/print",
    "user/apps/final_test",
    "subsystems/arch",
    "subsystems/config",
    "subsystems/ksync",
    "subsystems/constants",
    "subsystems/mem",
    "subsystems/vfs",
    "subsystems/devices",
    "subsystems/drivers",
    "subsystems/interrupt",
    "subsystems/device_interface",
    "subsystems/timer",
    "kernel",
    "subsystems/unwinder",
    "subsystems/knet",
]


[profile.release]
#lto = true
#codegen-units = 1

