[workspace]
resolver = "2"
members = [
    "kernel",
    "userlib",
    "subsystems/gmanager",
    "apps/slint-helper",
    "apps/cat",
    "apps/sleep",
    "apps/todo",
    "apps/printdemo",
    "apps/egui",
    "apps/sysinfo",
    "apps/init",
    "apps/ls",
    "apps/mkdir",
    "apps/pwd",
    "apps/shell",
    "apps/touch",
    "apps/run_test",
    "apps/slint",
    "apps/socket_test",
    "apps/tests",
    "apps/memory-game",
    "apps/print",
    "apps/final_test",
    "subsystems/arch",
    "subsystems/config",
    "subsystems/ksync",
    "subsystems/constants",
    "subsystems/mem",
    "subsystems/vfs",
    "subsystems/devices",
    "subsystems/drivers",
    "subsystems/interrupt",
    "subsystems/device_interface",
    "subsystems/timer",
    "kernel",
    "subsystems/unwinder",
    "subsystems/knet",
]


[profile.release]
lto = true
codegen-units = 1

