[workspace]
members = [
    "kernel",
    "userlib",
    "boot",
    "modules/gmanager",
    "modules/pci-rs",
    "modules/syscall-table",
    "modules/systable-macro-derive",
    "modules/plic",
    "modules/uart",
    "modules/syscall",
    "modules/basemachine",
    "modules/pager",
    "apps/cat",
    #    "apps/dbfs",
    "apps/init",
    "apps/ls",
    "apps/mkdir",
    "apps/pwd",
    "apps/shell",
    "apps/time",
    "apps/filetest_simple",
    "apps/forktest",
    "apps/hugewrite",
    "apps/dbwrite",
    "apps/hugeread",
    "apps/seektest",
    "apps/linktest",
    "apps/stattest",
    "apps/dirtest",
    "apps/attrtest",
    "apps/touch",
    "apps/attrtest1",
    "apps/pipetest",
    "apps/pipetest2",
    "apps/throughput",
    "apps/randrw",
    "apps/sequencewr",
    "apps/alloctest",
    "apps/mmmap",
    "apps/run_test",
    "apps/guitest",
]


[profile.release]
lto = true
codegen-units = 1
