[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["chen linfeng"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
### for log
log = "0.4.14"

### for other
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.2"

### for slab
rslab = {git= "https://github.com/os-module/rslab"}
preprint = "0.1.0"


### for riscv arch
riscv = "0.9.0"

### for memory manage
page-table = {path = "../../os-module/page-table"}
bitmap-allocator = {git = "https://github.com/rcore-os/bitmap-allocator"}
simple-bitmap = {path = "../modules/simple-bitmap" }

### for pid/tid alloc
gmanager = {path ="../modules/gmanager"}

### filesystem
xmas-elf = "0.9.0"
virtio-drivers = {git = "https://github.com/rcore-os/virtio-drivers"}
fdt = "0.1.3"
fat32 = {path = "../../os-module/fs/fat32"}
fat32-trait = {path ="../../os-module/fs/fat32-trait"}

lru = "0.9.0"
core2 = {version="0.4.0",default-features = false, features = ["nightly"]}
dbfs = {path="../../os-module/dbfs"}

### for test
cfg-if = "1.0.0"


[features]
default = ["test","dbfs"]
test = []
fat32 = []
dbfs = []
