[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["chen linfeng"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
spin = "0.9.2"
bitmap-allocator = {git = "https://github.com/rcore-os/bitmap-allocator"}
simple-bitmap = {path = "../dependence/simple-bitmap"}

rslab = {git= "https://github.com/os-module/rslab"}
preprint = "0.1.0"


