[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["chen linfeng"]

[dependencies]
log = "0.4.14"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.2"
riscv = "0.10.0"
bit_field = "0.10.1"
xmas-elf = "0.9.0"
bitflags = "1.3.2"
hashbrown = "0.13.2"
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers" }
fdt = "0.1.3"
volatile = "0.3"
onlyerror = { version = "0.1", default-features = false }
pci = { path = "../modules/pci-rs" }

embedded-graphics = "0.7.1"
tinybmp = "0.4.0"
rtc = { git = "https://github.com/os-module/rtc.git" }
lru = "0.9.0"
core2 = { version = "0.4.0", default-features = false, features = ["alloc"] }

### for memory manage
page-table = { git = "https://github.com/os-module/page-table.git", branch = "dev" }
#page-table = { path = "../../os-module/page-table" }
rvfs = { git = "https://github.com/Godones/rvfs.git" }
#rvfs = { path = "../../os-module/rvfs" }
fat32-vfs = { git = "https://github.com/Godones/fat32-vfs.git" }
#fat32-vfs = { path = "../../os-module/fat32-vfs" }

trace_lib = { git = "https://github.com/os-module/rtrace" }
preprint = "0.1.0"
rslab = "0.2.1"
syscall-table = { path = "../modules/syscall-table" }
plic = { path = "../modules/plic" }
uart = { path = "../modules/uart" }
pager = { path = "../modules/pager" }
gmanager = { path = "../modules/gmanager" }


[build-dependencies]
#syscall-table = {path = "../modules/syscall-table",features = ["std"]}
