[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["chen linfeng"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.2"
riscv = "0.10.0"


preprint = "0.1.0"
rslab = "0.2.1"

### for memory manage
page-table = {path = "../../os-module/page-table"}
simple-bitmap = {path = "../modules/simple-bitmap" }
gmanager = {path ="../modules/gmanager"}


xmas-elf = "0.9.0"
virtio-drivers = {git = "https://github.com/rcore-os/virtio-drivers",rev = "67183ee"}
fdt = "0.1.3"
pci = {path = "../modules/pci-rs"}
rtc = {path = "../../os-module/rtc"}


lru = "0.9.0"
core2 = {version="0.4.0",default-features = false, features = ["alloc"]}

rvfs = {path = "../../os-module/rvfs"}
fat32-vfs = {path = "../../os-module/fat32-vfs"}
jammdb = {path = "../../os-module/jammdb"}


[features]