[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["chen linfeng"]

[dependencies]
log = "0.4.14"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.2"
riscv = "0.10.0"

xmas-elf = "0.9.0"
virtio-drivers = {git = "https://github.com/rcore-os/virtio-drivers",rev = "67183ee"}
fdt = "0.1.3"

pci = {path = "../modules/pci-rs"}
rtc = {path = "../../os-module/rtc"}

lru = "0.9.0"
core2 = {version="0.4.0",default-features = false, features = ["alloc"]}
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

### for memory manage
page-table = {path = "../../os-module/page-table"}
simple-bitmap = {path = "../modules/simple-bitmap" }
gmanager = {path ="../modules/gmanager"}

rvfs = {path = "../../os-module/rvfs"}
fat32-vfs = {path = "../../os-module/fat32-vfs"}
jammdb = {path = "../../os-module/jammdb"}
dbfs2 = {path = "../../os-module/dbfs2"}

trace_lib = {git = "https://github.com/os-module/rtrace"}
preprint = "0.1.0"
rslab = "0.2.1"
syscall-table = {path = "../modules/syscall-table"}
dbop = {path = "../../os-module/dbop"}
plic = {path = "../modules/plic"}
uart = {path = "../modules/uart"}

[build-dependencies]
#syscall-table = {path = "../modules/syscall-table",features = ["std"]}

