[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["chen linfeng"]

[dependencies]
log = "0.4.14"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.2"
riscv = "0.10.0"
bit_field = "0.10.1"
xmas-elf = "0.9.0"
bitflags = "1.3.2"
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers", rev = "de1c3b130e507702f13d142b9bee55670a4a2858" }
fdt = "0.1.3"
embedded-graphics-core = "0.3.3"
tinybmp = "0.4.0"
rtc = { git = "https://github.com/os-module/rtc.git" }
lru = "0.10.0"
core2 = { version = "0.4.0", default-features = false, features = ["alloc"] }
cfg-if = "1.0.0"
### for memory manage
page-table = { git = "https://github.com/os-module/page-table.git", branch = "dev" }
#page-table = { path = "../../os-module/page-table" }
rvfs = { git = "https://github.com/Godones/rvfs.git" }
#rvfs = { path = "../../os-module/rvfs" }
fat32-vfs = { git = "https://github.com/Godones/fat32-vfs.git" }
#fat32-vfs = { path = "../../os-module/fat32-vfs" }
visionfive2-sd = { git = "https://github.com/os-module/visionfive2-sd.git", optional = true }
tracer = {git = "https://github.com/os-module/tracer"}
#
#tracer = {path = "../../os-modules/tracer"}

preprint = "0.1.0"
rslab = { version = "0.2.1" }
syscall-table = { git = "https://github.com/os-module/syscall-table.git" }
plic = { git = "https://github.com/os-module/plic" }

#pager = { git = "https://github.com/os-module/pager", default-features = false, optional = true }
pager = {path = "../../os-modules/pager",default-features = false, optional = true}
gmanager = { path = "../modules/gmanager" }
kernel-sync = { path = "../modules/kernel-sync", package = "lock" }
syscall_define = { path = "../modules/syscall", package = "syscall" }
basemachine = { path = "../modules/basemachine" }
uart = { path = "../modules/uart" }
schedule = { path = "../modules/schedule" }
talc = { version = "1.0", optional = true }
buddy_system_allocator = { version = "0.9.0", optional = true }

simple-net = { path = "../modules/simple-net" }
[dependencies.smoltcp]
git = "https://github.com/rcore-os/smoltcp.git"
rev = "2ade274"
default-features = false
features = [
    "alloc", "log", # no std
    "medium-ethernet",
    "proto-ipv4",
    "socket-raw", "socket-icmp", "socket-udp", "socket-tcp", "socket-dns",
]

[features]
default = ["pager_bitmap"]
vf2 = ["visionfive2-sd"]
cv1811h = []
hifive = []
qemu = []
net_test = []

slab = []
talloc = ["talc"]
buddy = ["buddy_system_allocator"]

pager_buddy = ["pager/buddy"]
pager_bitmap = ["pager/bitmap"]