[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["chen linfeng"]

[dependencies]
log = "0.4.14"
spin = "0.9.2"
riscv = "0.10.0"
bit_field = "0.10.1"
xmas-elf = "0.9.0"
bitflags = "1.3.2"
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers",rev = "4b60f5d"}
fdt = "0.1.3"
embedded-graphics-core = "0.3.3"
tinybmp = "0.4.0"
rtc = { git = "https://github.com/os-module/rtc.git" }
lru = "0.10.0"

cfg-if = "1.0.0"
page-table = { git = "https://github.com/os-module/page-table.git", branch = "dev" }

visionfive2-sd = { git = "https://github.com/os-module/visionfive2-sd.git", optional = true }
tracer = { git = "https://github.com/os-module/tracer" }
preprint = "0.1.0"
rslab = { version = "0.2.1", optional = true }

syscall-table = { git = "https://github.com/os-module/syscall-table.git" }
plic = { git = "https://github.com/os-module/plic" }
pager = { git = "https://github.com/os-module/pager", default-features = false, optional = true }
kernel-sync = { git = "https://github.com/os-module/kernel-sync.git" }
pconst = { git = "https://github.com/os-module/pconst.git", features = [
    "trick",
] }

#pconst = { path = "../../os-modules/pconst",features = ["trick"]}
gmanager = { path = "../modules/gmanager" }
basemachine = { path = "../modules/basemachine" }
uart16550 = { version = "0.0.1", optional = true }
uart8250 = { git = "https://github.com/os-module/uart-rs.git", optional = true }
smpscheduler = { git = "https://github.com/os-module/smpscheduler.git" }
talc = { version = "1.0", optional = true }
buddy_system_allocator = { version = "0.9.0", optional = true }

downcast-rs = { version = "1.2.0", default-features = false }

vfscore = { git = "https://github.com/os-module/rvfs.git", features = [
    "linux_error",
] }
devfs = { git = "https://github.com/os-module/rvfs.git" }
dynfs = { git = "https://github.com/os-module/rvfs.git" }
ramfs = { git = "https://github.com/os-module/rvfs.git" }
fat-vfs = { git = "https://github.com/os-module/rvfs.git" }

# vfscore = { path = "../../os-modules/rvfs/vfscore", features = ["linux_error"] }
# devfs = { path = "../../os-modules/rvfs/devfs" }
# dynfs = { path = "../../os-modules/rvfs/dynfs" }
# ramfs = { path = "../../os-modules/rvfs/ramfs" }
# fat-vfs = { path = "../../os-modules/rvfs/fat-vfs" }

#loopback = {path = "../../os-modules/simple-net/loopback", optional = true}
#virtio-net = {path = "../../os-modules/simple-net/virtio-net"}
#netcore = {path = "../../os-modules/simple-net/netcore"}

loopback = {git = "https://github.com/os-module/simple-net",optional = true}
virtio-net = {git = "https://github.com/os-module/simple-net"}
netcore = {git = "https://github.com/os-module/simple-net"}

[dependencies.smoltcp]
git = "https://github.com/rcore-os/smoltcp.git"
rev = "2ade274"
default-features = false
features = [
    "alloc",
    "log",             # no std
    "medium-ethernet",
    "proto-ipv4",
    "socket-raw",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    "socket-dns",
]

[features]
default = ["pager_bitmap","test"]
vf2 = ["visionfive2-sd", "uart8250"]
cv1811h = []
hifive = ["uart16550"]
qemu = ["uart16550"]
net_test = []

slab = ["rslab"]
talloc = ["talc"]
buddy = ["buddy_system_allocator"]

pager_buddy = ["pager/buddy"]
pager_bitmap = ["pager/bitmap"]

test = ["loopback"]
