[package]
name = "knet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { path = "../constants" }
ksync = { path = "../ksync" }
netcore = {git = "https://github.com/os-module/simple-net"}
vfs = { path = "../vfs" }
vfscore = { git = "https://github.com/os-module/rvfs.git", features = [
    "linux_error",
] }

log = "0"