[package]
name = "throughput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Mstd = { path = "../../userlib" }



[features]
default = ["4k"]
8k = []
4k = []
1k = []
512 = []
